routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
\Illuminate\Support\Facades\Broadcast::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'web'], function () {
    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
        Route::get('create', ['uses' => 'BlogController@create', 'as' => 'create']);
        Route::post('store', ['uses' => 'BlogController@store', 'as' => 'store']);
        Route::get('{blog}', ['uses' => 'BlogController@show', 'as' => 'show']);
        Route::post('{blog}/comment', ['uses' => 'BlogController@comment', 'as' => 'comment']);
    });
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{

    protected $guarded = [];

    protected $dates = [
        'created_at'
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function comments() {
        return $this->hasMany(Comment::class);
    }

    public function getTitle() {
        return $this->title;
    }

    public function setTitle($title) {
        $this->title = $title;
        return $this;
    }

    public function getBody() {
        return $this->body;
    }

    public function setBody($body) {
        $this->body = $body;
        return $this;
    }

    public function getCreatedAt() {
        return $this->created_at;
    }

    public function attachComment($data) {
        return $this->comments()->create([
            'body' => $data->body,
            'user_id' => auth()->id()
        ]);
    }
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $guarded = [];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function setBody($body) {
        $this->body = $body;
        return $this;
    }

    public function setUserId($id) {
        $this->user_id = $id;
        return $this;
    }

    public function setBlogId($id) {
        $this->blog_id = $id;
        return $this;
    }

    public function getBody() {
        return $this->body;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdmin() : bool {
        return (bool) $this->is_admin;
    }

    public function logoutAuthenticatedUser() {
        return Auth::logout();
    }

    public function blogs() {
        return $this->hasMany(Blog::class);
    }

    public function getName() {
        return $this->name;
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use App\Comment;
use App\Events\NewComment;
use App\Http\Requests\CreateBlogRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class BlogController extends Controller
{
    public function show(Blog $blog) {
        $comments = $blog->comments()->with('user')->get();
        return view('blogs.show', compact('blog', 'comments'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create() {
        return view('blogs.create');
    }

    /**
     * @param CreateBlogRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateBlogRequest $request) {
        // Kijk in de request of de blog is aangemaakt, zo ja: notification
        if ($request->isValid())
            return redirect()->route('home')->with('notification', ['type' => 'success', 'message' => "Succesvol een blog aangemaakt"]);

        return redirect()->route('home')->with('notification', ['type' => 'danger', 'message' => "Succesvol geen blog aangemaakt"]);
    }

    /**
     * @param Request $request
     * @param Blog $blog
     * @return \Illuminate\Http\RedirectResponse
     */
    public function comment(Request $request, Blog $blog) {

        $comment = new Comment;
        $comment
            ->setBody($request->body)
            ->setUserId(auth()->id())
            ->setBlogId($blog->id)
            ->save();

        // Manier 2:
        // Via de model een nieuwe comment aan laten maken, zodat we de controller alleen gebruiken voor het afhandelen
        // waar het oorspronkelijk voor gemaakt is in de MVC structuur.

//        $comment = $blog->attachComment((object)$request->all());

        event(new NewComment($comment));

        if (!$comment){
            return redirect()->back()->with('notification', ['type' => 'danger', 'message' => "Succesvol geen comment aangemaakt"]);
        }

        return redirect()->back()->with('notification', ['type' => 'success', 'message' => "Succesvol een comment aangemaakt"]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $blogs = Blog::with('user')->orderBy('id', 'DESC')->get();
        return view('home', compact('blogs'));
    }
}

resources/views/blogs/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('blog.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="title">Titel</label>
                                <input type="text" name="title" placeholder="Titel" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="body">Body</label>
                                <textarea class="form-control" name="body" id="" cols="30" rows="10"></textarea>
                            </div>

                            <div class="form-group">
                                <button class="btn btn-primary">Maak aan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/blogs/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        {{ $blog->getTitle() }}
                    </div>

                    <div class="card-body">
                        {!!  $blog->getBody() !!}
                    </div>

                    <div class="card-footer">
                        Aangemaakt op: {{ $blog->getCreatedAt()->format('Y-m-d') }}
                    </div>
                </div>

                <div class="card mt-4">
                    <div class="card-header">Comments</div>
                    <div class="card-body">
                        <form action="{{ route('blog.comment', ['blog' => $blog]) }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="comment">Bericht</label>
                                <textarea class="form-control" id="comment" name="body" cols="30" rows="5"></textarea>
                            </div>
                            <button class="btn btn-primary">Maak bericht</button>
                        </form>

                        <hr>

                        <div>
                            <comment-component :blog="{{ $blog }}" :comments="{{ $comments }}"></comment-component>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Alle blogs</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table class="w-100">
                        <thead>
                            <tr>
                                <th>Titel</th>
                                <th>User</th>
                                <th>Aangemaakt op</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($blogs as $blog)
                                <tr>
                                    <td>
                                        <a href="{{ route('blog.show', ['blog' => $blog]) }}">{{ $blog->getTitle() }}</a>
                                    </td>
                                    <td>{{ $blog->user->getName() }}</td>
                                    <td>{{ $blog->getCreatedAt()->format('Y-m-d') }}</td>
                                    <td>
                                        <button class="btn btn-sm btn-danger">Verwijder</button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @if(Session::has('notification'))

                <div class="container">
                    <div class="col-md-8">
                        <div class="alert alert-{{Session::get('notification.type')}}" role="alert">
                            {{Session::get('notification.message')}}
                        </div>
                    </div>
                </div>

            @endif
            @yield('content')
        </main>
    </div>
</body>
</html>